apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sparkoperator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - delete
  - update

